# Form implementation generated from reading ui file 'c:\PycharmProjects\lotnisko\GUI\flight_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 500)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_calendar = QtWidgets.QVBoxLayout()
        self.verticalLayout_calendar.setObjectName("verticalLayout_calendar")
        self.label_plane = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_plane.setFont(font)
        self.label_plane.setObjectName("label_plane")
        self.verticalLayout_calendar.addWidget(self.label_plane)
        self.comboBox_plane = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_plane.setObjectName("comboBox_plane")
        self.verticalLayout_calendar.addWidget(self.comboBox_plane)
        self.label_from = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_from.setFont(font)
        self.label_from.setObjectName("label_from")
        self.verticalLayout_calendar.addWidget(self.label_from)
        self.lineEdit_from = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_from.setText("")
        self.lineEdit_from.setObjectName("lineEdit_from")
        self.verticalLayout_calendar.addWidget(self.lineEdit_from)
        self.comboBox_from = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_from.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_from.sizePolicy().hasHeightForWidth())
        self.comboBox_from.setSizePolicy(sizePolicy)
        self.comboBox_from.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBox_from.setObjectName("comboBox_from")
        self.verticalLayout_calendar.addWidget(self.comboBox_from)
        self.label_to = QtWidgets.QLabel(parent=Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_to.setFont(font)
        self.label_to.setObjectName("label_to")
        self.verticalLayout_calendar.addWidget(self.label_to)
        self.lineEdit_to = QtWidgets.QLineEdit(parent=Dialog)
        self.lineEdit_to.setObjectName("lineEdit_to")
        self.verticalLayout_calendar.addWidget(self.lineEdit_to)
        self.comboBox_to = QtWidgets.QComboBox(parent=Dialog)
        self.comboBox_to.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_to.sizePolicy().hasHeightForWidth())
        self.comboBox_to.setSizePolicy(sizePolicy)
        self.comboBox_to.setMinimumSize(QtCore.QSize(250, 0))
        self.comboBox_to.setObjectName("comboBox_to")
        self.verticalLayout_calendar.addWidget(self.comboBox_to)
        self.calendarWidget = QtWidgets.QCalendarWidget(parent=Dialog)
        self.calendarWidget.setObjectName("calendarWidget")
        self.verticalLayout_calendar.addWidget(self.calendarWidget)
        self.timeEdit = QtWidgets.QTimeEdit(parent=Dialog)
        self.timeEdit.setObjectName("timeEdit")
        self.verticalLayout_calendar.addWidget(self.timeEdit)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_calendar.addWidget(self.buttonBox)
        self.horizontalLayout.addLayout(self.verticalLayout_calendar)
        self.verticalLayout_3.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_plane.setText(_translate("Dialog", "Plane:"))
        self.label_from.setText(_translate("Dialog", "From:"))
        self.lineEdit_from.setToolTip(_translate("Dialog", "<html><head/><body><p><br/></p></body></html>"))
        self.label_to.setText(_translate("Dialog", "To:"))
